# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
AllCops:
  TargetRubyVersion: 2.5

  # Don't check binstubs or gemfile
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/*_helper.rb'

Layout/EmptyLineAfterMagicComment:
  Enabled: false

# Allow braces for blocks that mainly return a value, including RSpec lets and
# subjects
Style/BlockDelimiters:
  EnforcedStyle: semantic

# Don't require a class comment
Style/Documentation:
  Enabled: false

# Require trailing commas for multiline arrays
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

# Require trailing commas for multiline arrays
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Allow but do not require modifier usage of if/unless
Style/IfUnlessModifier:
  Enabled: false

Metrics/LineLength:
  Max: 100
